name: Code Quality Check

# When to run this workflow
on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Get the code
    - name: Checkout code
      uses: actions/checkout@v4
    
    # Step 2: Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm ci
    
    # Step 4: Run linting
    - name: Run ESLint
      run: npm run lint
    
    # Step 5: Check formatting
    - name: Check Prettier formatting
      run: npm run format:check
    
    # Step 6: Run tests
    - name: Run tests
      run: npm run test
    
    # Step 7: Build project (if applicable)
    - name: Build project
      run: npm run build